### ISSUE TITLE
Inheritance!

### ISSUE THREAD

**Issue by benjohnsonnlp** [adamcorpora/DungeonsAndAdams#2]
Instead of Character having string to represent the profession, we are going to have different classes for different professions, because they often work very differently.

Create a Fighter, Wizard, Priest, Rogue class.

Fighters have an `.actionSurge()` method

Wizards can cast spells `.cast(String spell)`

Priests can cast spells `.cast(String spell)` and turn undead `.turnUndead()`

Rogues have a `.sneakAttack()`

All of them should be able to have their primary stats and equip weapons.

**Comment by adamcorpora** [comment]
I've created the subclasses for the four professions, as well as two other classes for "Spellcasters" and "Offense". But when I try to use extends on those two classes, it won't let me. It says there's no default constructor, which I don't understand. I have Wizard extending to Spellcaster. I have Spellcaster extending to Character. But they don't like that second extend. Any idea why?

**Comment by adamcorpora** [comment]
Ben, I messed up something. I accidentally merged something and then I went to History and reverted a few files and now everything great except my "Character.java" file is red and has 13 warnings and I can't commit. Help!
